version: "3.4"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
  api-gateway:
    image: api-gateway
    container_name: api-gateway
    ports:
      - "80:80"
    build:
      context: .
      dockerfile: DockerfileApiGateway
  service-a:
    image: service-a
    container_name: service-a
    build:
      context: .
      dockerfile: DockerfileServiceA
  service-b:
    image: service-b
    container_name: service-b
    build:
      context: .
      dockerfile: DockerfileServiceB
  service-c:
    image: service-c
    container_name: service-c
    build:
      context: .
      dockerfile: DockerfileServiceC